# Site
#repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
repository: stepha-tan/stepha-tan.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Stephanie Tan
title: PhD researcher
email: stephanietan0514@gmail.com
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

# Social links
#github_username:  jekyll
linkedin_username: stephanie-tan-16811a8a
# researchgate_username: Stephanie-Tan

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/stephanietan.jpg
about_content: | # this will include new lines to allow paragraphs
  I have a technical and multidisciplinary background, having trainings in both computer science and applied sciences. I'm currently a PhD reseaercher in <a href="https://www.tudelft.nl/en/ewi/over-de-faculteit/afdelingen/intelligent-systems/pattern-recognition-bioinformatics/socially-perceptive-computing-lab" target="_blank">Socially Perceptive Computing Lab</a> of TU Delft.
  My research focuses on automatic analysis of individual head and body behaviors in face-to-face social interactions and the connection to the inpretation of the underlying social dynamics, such as conversational group evolution. 

  My interests and expertise span various in applied and multimodal machine learning/deep learning: 
    - Time-series data 
    - Social signal processing
    - Wearable sensors
    - Individual and group behaviour

  I'm passionate about designing data-driven solutions for real-life applications, and making products out of them to drive impact. 
    
# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
